apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-go
  template:
    metadata:
      labels:
        app: app-go
    spec:
      containers:

      - name: app-go
        image: golang:1.7.0-alpine

        ports: 
        - name: http
          containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: app-go-service
spec:
  selector: 
    app: app-go
  type: LoadBalancer
  ports:
  - name: http
    port: 8000