apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  replicas: 1 

  selector: #selector utilizado para criar o service
    matchLabels:
      app: mysql-server
      tier: db

  template: #referente ao POD
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec: #spec do POD
      containers:
      - image: mysql:5.7
        name: mysql-server
        args:
          - "--ignore-db-dir=lost+found" #ignora arquivo lost+found
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: # kubectl create secret generic mysql-pass-literal='a1s2d3f4'
              name:  mysql-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim